set -g default-terminal "tmux-256color"
set -s escape-time 0
set -g base-index 1
set -g renumber-windows on
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g status-position top
set -g window-status-current-style "fg=pink bold"
set -g status-right ""

# optional -- i like C-a not C-b (pure preference)
# unbind C-b
set-option -g prefix C-b
bind-key C-b send-prefix

# vi key movement for copy/pasta mode
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# <WHERE YOUR TMUX CONF GOES> = XDG_CONFIG_HOME/tmux/tmux.conf
# <WHERE YOUR TMUX CONF GOES> = ~/.tmux.conf
bind r source-file $HOME/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Bindeo para moverme como vim entre las terminales
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# unbind-key L
bind-key l switch-client -l

bind O run-shell "tmux neww ~/.local/scripts/open-pdf"
bind-key -r f run-shell "tmux neww ~/.local/scripts/tmux-sessionizer"
bind H run-shell "~/.local/scripts/tmux-sessionizer ~"
bind D run-shell "~/.local/scripts/tmux-sessionizer ~/.config"
bind P run-shell "~/.local/scripts/tmux-sessionizer ~/personal/projects"
bind N run-shell "~/.local/scripts/tmux-sessionizer ~/personal/notes"
bind N run-shell "~/.local/scripts/tmux-sessionizer ~/personal/notes"


bind-key c new-window -c "#{pane_current_path}"

# habilita selección y scroll con el ratón
set -g mouse on

# Scroll mas amplio, el default es 2000
set-option -g history-limit 200000
