image=/home/ernesto/Pictures/wallpapers/fondo.jpg
clock
indicator
indicator-radius=100
indicator-thickness=7
effect-blur=7x5
effect-vignette=0.5:0.5
ring-color=e0699e
key-hl-color=CC5A7B
bs-hl-color=C4788D
wrong-color=CC5A7B
inside-color=2A2A2A88
line-color=00000000
separator-color=00000000
grace=2
fade-in=0.2
