image=/home/ernesto/Pictures/wallpapers/fondo.jpg
clock
indicator
indicator-radius=100
indicator-thickness=7
effect-blur=7x5
effect-vignette=0.5:0.5
ring-color=e6bd5f
key-hl-color=a8b06a
bs-hl-color=cf6b5c
wrong-color=cf6b5c
inside-color=1c1b1a88
line-color=00000000
separator-color=00000000
grace=2
fade-in=0.2
