set -g status-style "bg=default,fg=#b3ac9d"
set -g window-status-current-style "fg=#e6bd5f bold"
set -g window-status-style "fg=#8a8272"
set -g pane-border-style "fg=#403c37"
set -g pane-active-border-style "fg=#e6bd5f"
set -g message-style "bg=#242322,fg=#ece4cd"
