#!/usr/bin/env bash

DIRS=(
    "$HOME/Downloads"
    "$HOME/Desktop"
    "$HOME/personal"
    "$(tmux run "echo #{pane_start_path}")"
)

# Agrupamos todos los directorios a ignorar dentro de \( ... \) antes de aplicar -prune
selected=$(find -L "${DIRS[@]}" -mindepth 1 \
    \( -path "$HOME/Desktop/Facu (Local)" \
       -o -name ".nix-profile" \
       -o -name ".cache" \
       -o -name ".git" \
       -o -name "node_modules" \
       -o -name ".local" \
       -o -name ".npm" \
       -o -name ".stack" \
       -o -name "$HOME/Desktop/backup" \
    \) -prune \
    -o -name "*.pdf" -print | sed "s|^$HOME/||" | sort -u | fzf)

if [[ -n "$selected" ]]; then
  selected="$HOME/$selected"
fi

if [[ -z "$selected" ]]; then
  exit 1
fi

selected_name=$(basename "$selected" | tr ".,: " "____")

swaymsg exec "sioyek \"$selected\"" > /dev/null 2>&1

exit 0
