#!/usr/bin/env bash

DIRS=(
    "$HOME/Desktop"
    "$HOME/personal"
    "$HOME/personal/notes"
    "$HOME/personal/projects"
)

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find ${DIRS[@]} -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z "$selected" ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr ".,: " "____")

switch_to() {
  if [[ -z "$TMUX" ]]; then
    tmux attach-session -t="$selected_name"
  else
    tmux switch-client -t="$selected_name"
  fi
}

if tmux has-session -t=$selected_name 2> /dev/null; then
  switch_to
  exit 0
fi

tmux new-session  -ds $selected_name -c $selected
switch_to
tmux send-key -t $selected_name "$HOME/.local/scripts/ready-tmux" 
